services:
  web:
    container_name: blog_web
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    networks:
      - backend
    volumes:
      - .:/app
    ports:
      - 8000:5000
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
    # tty: true
    command:
      [
        "gunicorn",
        "--config",
        "./src/config/gunicorn.py",
        "start:app"
      ]
    # command: bash -c "flask --app start:app run --host 0.0.0.0"
    init: true
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    networks:
      - backend
    privileged: true
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./compose/dev/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./compose/dev/mysql/config:/etc/mysql/conf.d
    env_file:
      - .env
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - backend
    env_file:
      - .env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: always

networks:
  backend:


volumes:
  mysql_data:
