services:
  redis:
    build: ./compose/dev/redis/master/
    # image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - ./compose/dev/redis/master/redis.conf:/redis.conf
    env_file:
      - .env
    restart: always
    command:
      [
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--masterauth",
        "${REDIS_PASSWORD}",
      ]
  redis_1:
    build: ./compose/dev/redis/master/
    ports:
      - 6380:6380
    networks:
      - backend
    volumes:
      - ./compose/dev/redis/replica/redis.conf:/redis.conf
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    command:
      [
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--masterauth",
        "${REDIS_PASSWORD}",
      ]
  redis_2:
    build: ./compose/dev/redis/master/
    ports:
      - 6381:6380
    networks:
      - backend
    volumes:
      - ./compose/dev/redis/replica/redis.conf:/redis.conf
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    command:
      [
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--masterauth",
        "${REDIS_PASSWORD}",
      ]
  sentinel_1:
    build: ./compose/dev/redis/sentinel/
    ports:
      - 26379:26379
    volumes:
      - ./compose/dev/redis/sentinel/sentinel_1.conf:/sentinel.conf
    env_file:
      - .env
    restart: always
    command: ["--sentinel", "auth-pass", "redis", "${REDIS_PASSWORD}"]
  sentinel_2:
    build: ./compose/dev/redis/sentinel/
    ports:
      - 26380:26380
    volumes:
      - ./compose/dev/redis/sentinel/sentinel_2.conf:/sentinel.conf
    env_file:
      - .env
    restart: always
    command: ["--sentinel", "auth-pass", "redis", "${REDIS_PASSWORD}"]
  sentinel_3:
    build: ./compose/dev/redis/sentinel/
    ports:
      - 26381:26381
    volumes:
      - ./compose/dev/redis/sentinel/sentinel_3.conf:/sentinel.conf
    env_file:
      - .env
    restart: always
    command: ["--sentinel", "auth-pass", "redis", "${REDIS_PASSWORD}"]
